name: Policy Test

on:
  push:
    branches:
      - master
      - ci-test
  pull_request:
    branches:
      - master
      - ci-test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        with:
          path: policies

      - name: Clone Kyverno
        run: git clone https://github.com/kyverno/kyverno --branch main

      - name: Set up Go 
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.5
        with:
          go-version: 1.17

      - name: Cache Go modules
        uses: actions/cache@d9747005de0f7240e5d35a68dca96b3f41b8b340 # v1.2.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: List directories
        run: ls

      - name: Test Policy
        run: |
          cd kyverno
          go run cmd/cli/kubectl-kyverno/main.go test ../policies
      
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2.4.0

  #     - name: Get Kyverno
  #       run: |
  #         curl -sL `
  #           curl -sL https://api.github.com/repos/kyverno/kyverno/releases/latest \
  #           | jq -r '.assets[].browser_download_url' \
  #           | grep linux_x86_64 \
  #         ` | tar xvz -C /usr/local/bin

  #     - name: Kyverno test
  #       run: kyverno test .

